# Generated by Django 4.2.11 on 2026-05-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='queueticket',
            new_name='queue_queue_hospita_c4de1b_idx',
            old_name='queue_queu_hospital_7658b7_idx',
        ),
        migrations.RenameIndex(
            model_name='queueticket',
            new_name='queue_queue_hospita_344740_idx',
            old_name='queue_queu_hospital_926a3e_idx',
        ),
    ]
