# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='plan',
            field=models.CharField(
                choices=[
                    ('trial', 'Trial'),
                    ('basic', 'Basic'),
                    ('advanced', 'Advanced'),
                    ('enterprise', 'Enterprise'),
                ],
                default='trial',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_beds',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
