# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_update_subscription_plan_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='billing_cycle_months',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Monthly'),
                    (3, '3 months'),
                    (12, '12 months'),
                    (24, '24 months'),
                ],
                default=1,
            ),
        ),
    ]
