# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('super_admin', 'Super Admin'),
                    ('hospital_admin', 'Hospital Admin'),
                    ('doctor', 'Doctor'),
                    ('receptionist', 'Receptionist'),
                    ('nurse', 'Nurse'),
                    ('lab_technician', 'Lab Technician'),
                    ('pharmacist', 'Pharmacist'),
                ],
                default='receptionist',
                max_length=30,
            ),
        ),
    ]
